export const DIALOG_TYPE = {
  ADD: 1,
  UPD: 2,
};
export const CUSTOMER_ORDER_STATUS={
  TASLAK:10,
  SIPARIS_OLUSTURULDU:11,
  ONAYLANMIS:20,
  ISIL_ISLEMDE:21,
  IPTAL_EDILDI:30,
  TAMAMLANDI:40,
  SEVKEDILIYOR:50,
  KAPANDI:60,
};
export const CUSTOMER_ORDER_ITEM_STATUS={
  TASLAK:10,
  ONAYLANMIS:20,
  ISIL_ISLEMDE:21,
  IPTAL_EDILMIS:30,
  TAMAMLANDI:40,
  SEVKEDILIYOR:50,
  KAPANDI:60,
};
export const WORK_ORDER_STATUS = {
  TASLAK:10,
  ONAYLANDI:20,
  ISIL_ISLEMDE:30,
  IPTAL_EDILMIS:40,
  TAMAMLANDI:50,
  KAPANDI:60,
};
export const WORK_ORDER_ITEM_STATUS = {
  TASLAK:10,
  BASLAMADI:20,
  DEVAM_EDIYOR:30,
  DURDURULDU:40,
  TAMAMLANDI:50,
  KAPANDI:60,
};